<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
	</head>
	<body>
		<div style="width: 80%;height: 800px;border: 3px solid blue;margin: 0 auto;">
			<img src="banner.jpg" width="100%" height="30%" style="margin-top: 0 auto;"/>
			<table border="2px solid blue;" width="100%" align="center" height="40px" style="background-color: lightskyblue;margin-top:-5px;">
				<tr style="font-size: 15px;color:blue;text-align: center;">
					<td width="100px">首页</td>
					<td>走进新疆</td>
					<td>民族习俗	</td>
					<td>吃在新疆</td>
					<td>最优选择</td>
					<td>特色线路	</td>
					<td>户外探险	</td>
					<td>精彩游记</td>
					<td>付款方式</td>
					<td>给我留言</td>
				</tr>
			</table>
			<div style="width: 100%;height:60%;border: 1px solid white;margin: 0 auto;background-color: skyblue;">
				<div style="width: 25%;height: 100%;position: relative;border: 1px solid white;">
					<img src="weather.jpg"width="100%" height="10%" align="left" style="margin-top: 0 auto;"/>
					<b style="color: whitesmoke;position: relative;left: 60%;top: -5%;">天气预报</b>
					<dl border="2px solid white;"  style=" position:relative;top: -5%;height:20%;width: 100%;background-color: skyblue;font-size: 13px;">
						<li>&nbsp;&nbsp;1.乌鲁木齐</li>
						<li>&nbsp;&nbsp;2.阿克苏</li>
						<li>&nbsp;&nbsp;3.昌吉</li>
						<li>&nbsp;&nbsp;4.阿勒泰</li>
						<li>&nbsp;&nbsp;5.哈密</li>
					</dl>
					<h3 style="position: relative;top: -10%;height: 30px;width: 100%;background-color: aliceblue;">
						<dl>
							<li>&nbsp;&nbsp;今日推荐</li>
						</dl>
					</h3>
					<div style="width: 100%;position: relative;left: 0;top: -13%;">
						<center>
							<img src="tuijian1.jpg" width="100%" height="70px" style="position: relative;"/>
							<p style="color: white;font-size: 12px;">香木河</ps>
							<img src="tuijian2.jpg" width="100%"height="70px"/>
							<p style="color: white;font-size: 12px;">白哈巴</p>
							<img src="tuijian3.jpg" width="100%" height="70px"/>
							<p style="color: white;font-size: 12px;">峰</p>
						</center>
					</div>
					
				</div>
				<div style="width: 50%;height: 100%;position: relative;left: 25%;top: -100%;border: 1px solid white;">
					<img src="ghost.jpg" width="100%" height="30%"/>
					<img src="picture_h1.gif" height="10%"/>
					<div style="width: 100%;height: 20%;">
						<img src="beauty1.jpg" width="20%" height="100%" style="float: left;margin-left: 5%;"/>
						<img src="beauty2.jpg" width="20%" height="100%" style="margin-left: 5%;"/>
						<img src="beauty3.jpg" width="20%" height="100%" style="margin-left: 5%;"/>
						<img src="beauty4.jpg" width="20%" height="100%" style="float: right;"/>
					</div>
					<img src="route_h1.gif" height="10%" style="margin-top: 10px;"/>
					<dl border="2px solid white;"  style=" position:relative;top: 0%;height:20%;width: 100%;background-color:white;font-size: 13px;">
						<li>&nbsp;&nbsp;1.乌鲁木齐</li>
						<li>&nbsp;&nbsp;2.阿克苏</li>
						<li>&nbsp;&nbsp;3.昌吉</li>
						<li>&nbsp;&nbsp;4.阿勒泰</li>
					</dl>
				</div>
				
				<div style="width: 25%;height: 100%;position:relative;left: 75%;top: -200%;border: 1px solid white;">
					<h3 style="position: relative;top: -5%;height: 30px;width: 100%;background-color: aliceblue;">
						&nbsp;&nbsp;新疆地图
					</h3>
					<div style="position: relative;top: -10%;width: 100%;height: 40%;">
						<img src="map1.jpg" width="100%" height="50%" />
						<img src="map2.jpg" width="100%" height="50%"/>
					</div>
					<h3 style="position: relative;top: -15%;height: 30px;width: 100%;background-color: aliceblue;">
						&nbsp;&nbsp;特色美食
					</h3>
					<dl border="2px solid white;"  style=" position:relative;top: -20%;height:20%;width: 100%;background-color: skyblue;font-size: 13px;">
						<li>&nbsp;&nbsp;1.乌鲁木齐</li>
						<li>&nbsp;&nbsp;2.阿克苏</li>
						<li>&nbsp;&nbsp;3.昌吉</li>
						<li>&nbsp;&nbsp;4.阿勒泰</li>
						<li>&nbsp;&nbsp;5.哈密</li>
					</dl>
					<h3 style="position: relative;top: -20%;height: 30px;width: 100%;background-color: aliceblue;">
						&nbsp;&nbsp;新疆住宿
					</h3>
					<dl border="2px solid white;"  style=" position:relative;top: -25%;height:20%;width: 100%;background-color: skyblue;font-size: 13px;">
						<li>&nbsp;&nbsp;1.乌鲁木齐</li>
						<li>&nbsp;&nbsp;2.阿克苏</li>
						<li>&nbsp;&nbsp;3.昌吉</li>
						<li>&nbsp;&nbsp;4.阿勒泰</li>
						<li>&nbsp;&nbsp;5.哈密</li>
					</dl>
				</div>
			</div>
			<div style="
						width: 100%; 
						height: 40px; 
						border: 0.5px solid white;
						margin: 0 auto;
						color: black;
						background-color:skyblue;
						">
						<center>
							<p style="font-size: 8px;">
						网页爱好者：黄骁 <b>C</b>版权所有2022-2032<br/>
						联系我们：3188053639@qq.com
							</p>
						</center>
			</div>
			
		</div>
		
	</body>
</html>
